FORMAT: 1A
HOST: http://localhost:3000/

# Harshita AI

Harshita AI API for CSC Operators, Community, and Email Services.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }
                ]
            }
        ]
