import React from 'react';
import { useStore } from '../store';

export default function DocumentWatermark() {
  const { subscriptionMode } = useStore();
  
  // PRD SUBSCRIPTION RULE:
  // if user.subscription == FREE (trial/expired) -> Watermark Visible
  // if user.subscription == PREMIUM (active) -> Hide Watermark
  const isPremium = subscriptionMode === 'active';
  
  if (isPremium) return null;

  return (
    <div 
      className="watermark-container"
      style={{
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-30deg)',
        opacity: 0.06,
        width: '60%',
        height: 'auto',
        pointerEvents: 'none',
        userSelect: 'none',
        zIndex: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      {/* Monogram */}
      <div 
        style={{
          fontSize: 'clamp(100px, 15vw, 250px)',
          fontWeight: '900',
          lineHeight: '1',
          color: '#000',
          fontFamily: 'serif',
          letterSpacing: '-0.05em'
        }}
      >
        HA
      </div>
      
      {/* Footer Text */}
      <div 
        style={{
          marginTop: '20px',
          textAlign: 'center',
          opacity: 0.3,
          fontSize: '10px',
          color: '#000',
          fontWeight: '600',
          fontFamily: 'sans-serif'
        }}
      >
        <div>Generated by Harshita AI</div>
        <div>www.n-dizi.in</div>
      </div>
    </div>
  );
}
